#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
xset -dpms
fbsetbg /home/sysad/Downloads/Start2.png
/usr/lib/vino/vino-server &
#chromium-browser --kiosk --incognito http://google.com

fluxbox &
fbpid=$!

sleep 1
{
sh /home/sysad/CelestraConfig/console-startup.sh &
} &
xmodmap /home/celestra/modmap
wait $fbpid

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

#exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/celestra/.fluxbox/log"
